swagger: '2.0'
info:
  description: >-
    API Service for Polly
  version: 1.0.0
  title: Polly API
  contact:
    email: matt@denvercliffs.com
host: polly-api.mattcliff.net
basePath: /dev
schemes:
  - https
paths:
  /:
    get:
      summary: Gets all customer records in the system
      tags:
        - customer
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: postId
          type: string
          description: customer object to add
          required: true
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/postitem'
    post:
      tags:
        - customer
      summary: Adds a new customer record
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: object to add
          required: true
          schema:
            $ref: '#/definitions/newpost'
      responses:
        '200':
          description: success
        '405':
          description: Invalid input
definitions:
  newpost:
    type: object
    properties:
      voice:
        type: string
        description: name of the voice to use
      text:
        type: string
        description: text to convert
  postitem:
    type: object
    properties:
      voice:
        type: string
        description: name of the voice to use
      text:
        type: string
        description: text to convert
