# uses aws/codebuild/nodejs:8.11.0
#
version: 0.2


phases:

  install:
    commands:
      - cd contactless && npm install -g serverless
  build:
    commands:
  post_build:
    commands:
      - serverless --stage=dev --verbose deploy --region $AWS_REGION
      - servlerless info --region $AWS_REGION

artifacts:
  files:
    - serverless.yml
